# Generated by Django 4.2.20 on 2025-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userrole_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
