# Generated by Django 4.2.20 on 2025-04-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userrole_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_admin",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_role__role_name": "Admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
